sudo: false

# "test" step configuration
language: ruby
rvm:
  - 2.6
  - 2.5
cache:
  bundler: true
bundler_args: --path vendor --local --without development
addons:
  code_climate:
    repo_token: a42e116d4d68894b025a60cb722a0b9ba2cf1c6497debb02993d0702284d2511
before_install:
  # Ensure an up-to-date bundler version is used, otherwise fails on Ruby 2.5
  - bundle update --bundler
before_script:
  - mysql -u root -e "CREATE DATABASE myapp_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON myapp_test.* TO 'travis'@'%';";
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - export DATABASE_URL="mysql2://travis@localhost/myapp_test"
script:
  - bin/rails db:migrate
  - RUN_COVERAGE=travis bin/rails test
  - bin/rails coverage:report

# "deploy" step configuration
jobs:
  include:
    - stage: deploy
      name: Build & publish new release (if needed)
      if: branch = master AND repo = "codeRIT/hackathon-manager"
      language: node_js
      node_js: lts/*
      cache:
        yarn: true
      before_install: skip
      before_script: skip
      script: yarn semantic-release
    - stage: deploy
      name: Push docs website update
      if: branch = master AND repo = "codeRIT/hackathon-manager"
      language: node_js
      node_js: lts/*
      cache:
        yarn: true
      before_install: skip
      before_script: skip
      script: bash website/travis-deploy.sh
