# This workflow runs on push to the HackEngine Github repo
name: Build & deploy documentation
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update gh-pages with docs
    steps:
      - name: Checkout this repo # 2
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install required gem dependencies
        run: gem install yard --no-document
      - name: Build YARD Ruby Documentation # 3
        run: yardoc --output-dir docs

    